# 配置端口
server:
  port: 8081
dubbo:
  # 配置服务信息
  application:
    name: dubbo-user
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://175.178.11.232:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 20880
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  profiles:
    active: dev