# Data Source
spring:
  datasource:
    password: weiwei145905
    username: root
    url: jdbc:mysql://120.55.85.54:3306/project?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  # Redis
  redis:
    host: 175.178.11.232
    port: 6379
    password: weiwei145905
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    timeout: 30000

# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.demo.dubbo.dto