# 配置端口
server:
  port: 8080
dubbo:
  # 配置服务信息
  application:
    name: dubbo-web
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: zookeeper://120.55.85.54:2181
  # 设置超时时间
  consumer:
    timeout: 60000
    check: false
    retries: 0
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  profiles:
    active: dev